### ISSUE TITLE
Widgets for multi-valued parameters

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/py-simput#4]
Enable/implement a dynamic widget for multi-valued parameters (e.g. tuples) similar to what has been done in the Vera example (http://kitware.github.io/simput/app/). It would be neat to be able to define a type for each field separately.

See picture below:

![image](https://user-images.githubusercontent.com/24410244/167850714-4939da6f-d453-4186-a0da-1ea1d9f8331a.png)

In this example we'd have tuples of (string, float64).

I would imagine the `model.yaml` to look like this:

```
MultiValuedTuples:
  _label: Multi-valued tuples
  _help: >-
    You can also define multiple types as a tuple, like this.
  type: [string,float64]
  size: -1
  initial:
    - ["a",1.0]
  domains:
  - type: UI
    properties:
      sizeControl: true
```
